##
## Worklow for deploying the playground application to Fly.io
##
name: Deploy Playground (Production)
on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group # ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build jar
        run: ./gradlew :playground:shadowJar
      - name: Deploy
        run: cd playground && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
